// <auto-generated />
using System;
using GFCM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GFCM.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GFCM.Models.Attendance", b =>
                {
                    b.Property<int>("attendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("attendanceId"));

                    b.Property<DateTime>("attendanceDate")
                        .HasColumnType("date");

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("checkInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("checkOutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("attendanceId");

                    b.HasIndex("branchId");

                    b.HasIndex("userId");

                    b.ToTable("attendances");
                });

            modelBuilder.Entity("GFCM.Models.BodyMetric", b =>
                {
                    b.Property<int>("bodyMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bodyMetricId"));

                    b.Property<double?>("bodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<double>("heightCm")
                        .HasColumnType("float");

                    b.Property<DateTime>("metricDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("muscleMassKg")
                        .HasColumnType("float");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<double>("weightKg")
                        .HasColumnType("float");

                    b.HasKey("bodyMetricId");

                    b.HasIndex("userId");

                    b.ToTable("bodyMetrics");
                });

            modelBuilder.Entity("GFCM.Models.Branch", b =>
                {
                    b.Property<int>("branchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("branchId"));

                    b.Property<string>("branchAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("openingHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("branchId");

                    b.ToTable("branches");
                });

            modelBuilder.Entity("GFCM.Models.ClassBooking", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("classScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("bookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("bookingStatus")
                        .HasColumnType("int");

                    b.HasKey("userId", "classScheduleId");

                    b.HasIndex("classScheduleId");

                    b.ToTable("classBookings");
                });

            modelBuilder.Entity("GFCM.Models.ClassSchedule", b =>
                {
                    b.Property<int>("classScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("classScheduleId"));

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("className")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("trainerProfileId")
                        .HasColumnType("int");

                    b.HasKey("classScheduleId");

                    b.HasIndex("branchId");

                    b.HasIndex("trainerProfileId");

                    b.ToTable("classSchedules");
                });

            modelBuilder.Entity("GFCM.Models.Equipment", b =>
                {
                    b.Property<int>("equipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("equipmentId"));

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<string>("equipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maintenanceStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("purchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("equipmentId");

                    b.HasIndex("branchId");

                    b.ToTable("equipment");
                });

            modelBuilder.Entity("GFCM.Models.Membership", b =>
                {
                    b.Property<int>("membershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("membershipId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("membershipPlanId")
                        .HasColumnType("int");

                    b.Property<int>("membershipStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("membershipId");

                    b.HasIndex("membershipPlanId");

                    b.HasIndex("userId");

                    b.ToTable("memberships");
                });

            modelBuilder.Entity("GFCM.Models.MembershipPlan", b =>
                {
                    b.Property<int>("membershipPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("membershipPlanId"));

                    b.Property<int>("durationInDays")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<int>("maxClassesPerMonth")
                        .HasColumnType("int");

                    b.Property<string>("planDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("planName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("planPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("membershipPlanId");

                    b.ToTable("membershipPlans");
                });

            modelBuilder.Entity("GFCM.Models.Payment", b =>
                {
                    b.Property<int>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymentId"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("membershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("paymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("paymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("paymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("paymentId");

                    b.HasIndex("membershipId");

                    b.HasIndex("userId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("GFCM.Models.TrainerProfile", b =>
                {
                    b.Property<int>("trainerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("trainerProfileId"));

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<string>("certificationDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("yearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("trainerProfileId");

                    b.HasIndex("branchId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("trainerProfiles");
                });

            modelBuilder.Entity("GFCM.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("GFCM.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("workoutPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("workoutPlanId"));

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("planDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("planTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("trainerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("workoutPlanId");

                    b.HasIndex("trainerProfileId");

                    b.HasIndex("userId");

                    b.ToTable("workoutPlans");
                });

            modelBuilder.Entity("GFCM.Models.Attendance", b =>
                {
                    b.HasOne("GFCM.Models.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFCM.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GFCM.Models.BodyMetric", b =>
                {
                    b.HasOne("GFCM.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("GFCM.Models.ClassBooking", b =>
                {
                    b.HasOne("GFCM.Models.ClassSchedule", "classSchedule")
                        .WithMany("bookings")
                        .HasForeignKey("classScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFCM.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classSchedule");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GFCM.Models.ClassSchedule", b =>
                {
                    b.HasOne("GFCM.Models.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFCM.Models.TrainerProfile", "trainerProfile")
                        .WithMany()
                        .HasForeignKey("trainerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");

                    b.Navigation("trainerProfile");
                });

            modelBuilder.Entity("GFCM.Models.Equipment", b =>
                {
                    b.HasOne("GFCM.Models.Branch", "branch")
                        .WithMany("equipment")
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");
                });

            modelBuilder.Entity("GFCM.Models.Membership", b =>
                {
                    b.HasOne("GFCM.Models.MembershipPlan", "membershipPlan")
                        .WithMany("memberships")
                        .HasForeignKey("membershipPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFCM.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("membershipPlan");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GFCM.Models.Payment", b =>
                {
                    b.HasOne("GFCM.Models.Membership", "membership")
                        .WithMany()
                        .HasForeignKey("membershipId");

                    b.HasOne("GFCM.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("membership");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GFCM.Models.TrainerProfile", b =>
                {
                    b.HasOne("GFCM.Models.Branch", "branch")
                        .WithMany("trainerProfiles")
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFCM.Models.User", "user")
                        .WithOne("trainerProfile")
                        .HasForeignKey("GFCM.Models.TrainerProfile", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GFCM.Models.WorkoutPlan", b =>
                {
                    b.HasOne("GFCM.Models.TrainerProfile", "trainerProfile")
                        .WithMany()
                        .HasForeignKey("trainerProfileId");

                    b.HasOne("GFCM.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("trainerProfile");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GFCM.Models.Branch", b =>
                {
                    b.Navigation("equipment");

                    b.Navigation("trainerProfiles");
                });

            modelBuilder.Entity("GFCM.Models.ClassSchedule", b =>
                {
                    b.Navigation("bookings");
                });

            modelBuilder.Entity("GFCM.Models.MembershipPlan", b =>
                {
                    b.Navigation("memberships");
                });

            modelBuilder.Entity("GFCM.Models.User", b =>
                {
                    b.Navigation("trainerProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
